#include "SteamCoreWebAsyncActionGetGlobalAchievementPercentagesForApp.h"

class UObject;
class USteamCoreWebAsyncActionGetGlobalAchievementPercentagesForApp;

USteamCoreWebAsyncActionGetGlobalAchievementPercentagesForApp* USteamCoreWebAsyncActionGetGlobalAchievementPercentagesForApp::GetGlobalAchievementPercentagesForAppAsync(UObject* WorldContextObject, const FString& GameID) {
    return NULL;
}

USteamCoreWebAsyncActionGetGlobalAchievementPercentagesForApp::USteamCoreWebAsyncActionGetGlobalAchievementPercentagesForApp() {
}

